all:
	g++ -Wall -pedantic -o SFMLtesti.bin sfml-test.cpp -lsfml-graphics -lsfml-window -lsfml-system

cb:
	g++ -Wall -pedantic -o ChessboardTest.bin chessboard-test.cpp -lsfml-graphics -lsfml-window -lsfml-system

